baseURL = "/"
title = "daylin morgan" # Site title.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.
publishDir = "public"
canonifyURLs = true


paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

#disqusShortname = "yourdiscussshortname" # Enable or disable Disqus.

[params] # theme parameters
    author = "Daylin Morgan" # Author's name.
    info = "Biomedical Engineering Grad Student" # Author's job title or info.
    description = "personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
    avatarurl = "images/avatar.png" # Contain the path of the optionnal avatar in the static folder.

    #footercontent = "Enter a text here." # Add footer content
    #fixedbarContent = "Do you want to know me more private?→" # Add fixedbar content
    #fixedbarContentAfter = "Thank You! Please share it if you like it→" # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = ["css/custom.css"]

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    # Bottom sns share
    snsShare = true # new add
    # Popular sns share
    # if you want add sns. please message!
    enableTwitterShare = true  # new add
    enableFacebookShare = true # new add
    #enableHatenaShare = true   # new add
    #enableLineShare = true     # new add
    enableLinkedInShare = true # new add

    #thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

    faIcons = true

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/daylinmorgan/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/tweetsbydaylin/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/daylinmorgan/"
[[params.social]]
    name = "Email"
    icon = "fas fa-envelope"
    weight = 4
    url = "mailto:me@dayl.in"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "posts"
[[menu.main]]
    name = "About"
    weight = 2
    url = "about"
[[menu.main]]
    name = "Publications"
    weight = 3
    url = "publications"

[params.education]
        [[params.education.list]]
            degree = "Ph.D. in Biomedical Enginerring"
            college = "The University of Texas at Austin"
            dates = "2018-present"
        [[params.education.list]]
            degree = "M.S. in Biomedical Engineering"
            college = "Arizona State University"
            dates = "2017-2018"
            thesis_title = "An Integrated Biomanufacturing Platform for the Large Scale Expansion and Differentiation of Neural Progenitor Cells"
        [[params.education.list]]
            degree = "B.S.E. in Biomedical Engineering"
            college = "Arizona State University"
            dates = "2013-2017"
# go modules
[module]
[[module.imports]]
path= "github.com/naro143/hugo-coder-portfolio"
